---
- name: Create users with Bash shell and add to sudo group
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /usr/bin/bash
    home: "{{ item.home }}"
    createhome: yes
    groups: sudo
  loop: "{{ users }}"
  become: yes
